Test version

diff --git a/.github/workflows/ci_container_matrix.yaml b/.github/workflows/ci_container_matrix.yaml
--- a/.github/workflows/ci_container_matrix.yaml
+++ b/.github/workflows/ci_container_matrix.yaml
@@ -3,7 +3,7 @@ name: CI
 on: [ push ]
 
 env:
-  cfengine_version: 3.21.3
+  CFENGINE_VERSION: 3.21.3
 
 jobs:
   upload:
@@ -29,7 +29,7 @@ jobs:
         if: steps.cache-binary.outputs.cache-hit != 'true'
         run: |
           mkdir -p "rpm/";
-          wget --quiet "https://cfengine-package-repos.s3.amazonaws.com/community_binaries/Community-${cfengine_version}/agent_rhel${{ matrix.from_rockylinux }}_x86_64/cfengine-community-${cfengine_version}-1.el${{ matrix.from_rockylinux }}.x86_64.rpm" --output-document "rpm/cfengine.rpm";
+          wget --quiet "https://cfengine-package-repos.s3.amazonaws.com/community_binaries/Community-${CFENGINE_VERSION}/agent_rhel${{ matrix.from_rockylinux }}_x86_64/cfengine-community-${CFENGINE_VERSION}-1.el${{ matrix.from_rockylinux }}.x86_64.rpm" --output-document "rpm/cfengine.rpm";
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v4
@@ -46,8 +46,11 @@ jobs:
             FROM_ROCKYLINUX=${{ matrix.from_rockylinux }}
           tags: ci-${{ matrix.container_type }}-${{ matrix.from_rockylinux }}:latest
 
-      - name: Debug
-        run: docker image ls
-
       - name: Check CFEngine binary reports expected version
-        run: docker run --rm --name "ci-${{ matrix.container_type }}-${{ matrix.from_rockylinux }}" --entrypoint /var/cfengine/bin/cf-agent "ci-${{ matrix.container_type }}-${{ matrix.from_rockylinux }}:latest" --version
+        run: |
+          REPORTED_VERSION="$(docker run --rm --name "ci-${{ matrix.container_type }}-${{ matrix.from_rockylinux }}" --entrypoint /var/cfengine/bin/cf-agent "ci-${{ matrix.container_type }}-${{ matrix.from_rockylinux }}:latest" --version)";
+          echo "Detected version '${REPORTED_VERSION}'";
+          if [ "${REPORTED_VERSION}" != "CFEngine Core ${CFENGINE_VERSION}" ]; then
+            echo "Detected version is not as expected, failing";
+            exit 1;
+          fi;
